version: 1.0.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: RtkwMr7BE6KI9HbNOVIVAQHWAPHVxKL5XjMpe2TM9gydlEWMfAhgsrp4yOEGzeiC

platform:
  - Any CPU

configuration:
  - Release

build:
  project: NSmtp.sln

before_build:
  - nuget restore .\NSmtp.sln

artifcats:
  - path: NSmtp\**\*.nupkg
    name: Nuget

test_script:
- ps: >-
    & .\coverage_report.bat $env:CONFIGURATION

    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

    & $coveralls --opencover -i GeneratedReports\CoverageReport.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

